version: '2.3'
services:
  statsd:
    image: prom/statsd-exporter:v0.12.2
    restart: unless-stopped
    expose:
      - "9125/udp"
      - "9102/tcp"
    networks:
      - {{NETWORK}}
    volumes:
      - ./mapping:/statsd-mappings/statsd-mapping.yml
    command: [--statsd.mapping-config=/statsd-mappings/statsd-mapping.yml]
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
networks:
  {{NETWORK}}:
    external: true
