version: '2.2'
services:
  node:
    build:
      context: ./build
    container_name: rnode
    restart: unless-stopped
    environment:
      - ADNL_PORT={{ADNL_PORT}}
      - VALIDATOR_NAME={{VALIDATOR_NAME}}
      - NETWORK_TYPE={{NETWORK_TYPE}}
      - CONFIGS_PATH=/ton-node/configs
      - STATSD_DOMAIN=statsd
      - STATSD_PORT=:9125
        #STAKE:
        #MSIG_ENABLE:
        #SDK_URL:
    ports:
      - {{ADNL_PORT}}:{{ADNL_PORT}}/udp
    networks:
      - {{NETWORK}}
    volumes:
      - ./configs/:/ton-node/configs/
      - ./scripts/:/ton-node/scripts/
      - ./logs/:/ton-node/logs/
      - DB:/ton-node/node_db/
      - /tmp/metrics/:/tmp/metrics/
    entrypoint: /ton-node/scripts/entrypoint.sh
    command: ["bash"]
    mem_limit: {{NODE_MEMORY}}
    logging:
      driver: json-file
      options:
        max-size: "1000m"
        max-file: "100"
    cap_add:
      - SYS_PTRACE
networks:
  {{NETWORK}}:
    external: true
volumes:
  DB:
