version: '2.2'
services:
  node:
    build:
      context: ./build
    container_name: ever-node
    restart: unless-stopped
    environment:
      - ADNL_PORT={{ADNL_PORT}}
      - NETWORK_TYPE={{NETWORK_TYPE}}
      - CONFIGS_PATH=/ever-node/configs
      - NODE_LOGS_DIR=/ever-node/logs
      - STATSD_DOMAIN=statsd
      - STATSD_PORT=9125
    ports:
      - {{ADNL_PORT}}:{{ADNL_PORT}}/udp
    networks:
      - {{NETWORK}}
    volumes:
      - ./configs/:/ever-node/configs/
      - ./scripts/:/ever-node/scripts/
      - ./logs/:/ever-node/logs/
      - ./node_db:/ever-node/node_db/
      - ./metrics/:/tmp/metrics/
    entrypoint: /ever-node/scripts/entrypoint.sh
    command: ["bash"]
    mem_limit: {{NODE_MEMORY}}
    logging:
      driver: json-file
      options:
        max-size: "1000m"
        max-file: "100"
    cap_add:
      - SYS_PTRACE
networks:
  {{NETWORK}}:
    external: true
